language: java
jdk: oraclejdk8
install: true
script:
- mvn package
deploy:
  provider: heroku
  api_key:
    secure: EFqmhOZa5t77BrSDVysUM7H2FDP2sORex/9EEp/Tpgs+XmUtSO9+fzzIA+pgA2Xvog9dU4dabSNHBPog1gmUWXg/Jus3QyFb/a43e681T4W0xpdKjBZh0FNRrUppBWmoWdQYlheSV07Cl+22tHNeN7zctYBpEjkqz/X41I+ncDl8YnnoV9U80L/ESY2ipPF3HHpuZNaXROgHgXctQMtQkP9o+6wn/2QbHppGygPs2IQiYnPcz8nydZf3IjCM2oJzSyRSwVuhd4RbaYnr+FgOWINDR5kCiBb1FO8iClZ8m0M4mKXS410Hkn6LHsEUVSjotfvuv6Gg+QG/H376AQs5UASx+87AWW52coKT9ikBrwCaWRHFmeonG/kbanT80U5yZUTZZcD7El3tqXCrFGhFwPZgirSJb33QvkUGrUCeb/X0F5t1MmIEkiBbVseYllAUm+KUNFjh65JTXevoWn5DTTbuRGegsiOS/Wk7xd9eRpqcpVfTU7yKMZMO3sGlM0g9I35JDfjldBqqdxyvEk+mkDqErRa8Y5vtdAmOLzzKgxpwJq/yk/IN3pb1U5cWZAgVzOkysHrWueyDkJnEBosw/5Qc9B33MHdjS0zPy1E0KYn8qe7PjvvVqgZ0MhEVXEj8/OhcTsRhEol6nRCDudQ5BnFKp2f9a6G57ZTCVvU9N28=
  app: trip4u
  on:
    repo: night-fury-devs/Trip4U
    branch: dev
notifications:
  email: false
  slack:
    secure: g5kmKvZM7wJGEYS4nrpanNmzK+n59ZkkUnY7jG1zpNFZ360RZqmCOUmFZpsowihvyLLiJss3ZcpYKmQRSeA8eCjMpjUJJ9RQwj1aOewLZYNzZ577AgrqYgF43ewT5o2FP/LXUGsuCaRXHYtfDHBOuygJzbRBr6EYv4fLh3x1RiSDxIbliH0K8F4Aao4yF/It0PhQpe3Megk0PGNl8KhkuReWT+V8lMee2jom5OHPpyAVANArfcWdXkt/FMUix5qeV5ab+1mZjgnGSH5t+nC/pR4s6dImkbuNtKDEm9KqpZhhg2Tp+W5fe5DmItU1IPZmRn7LeyB6RkDIfmp+akUkopIi/n7kb4SuWb3/FWuv9OhKwVJzpt6PXKNlycgFetmKMiIpCCVA6J4Yj6NuKV6ZCnmKlKcUsC/mq9hzeA+fhRxOti7sbucbNv5NzJlwLvYR2H/KHtnFfqomu24GwwOKyrO7+vpHNy6IoYhozXRyFJRup9pVhwlRc6c2RhmOd1+8X5JbridYi/jY2rQ/6gBOtzM2g90ER39eT8I2hHurjS3Sz9P9aaxxKcd2EN33IZhxh3IvKyHfFjGqfl6h3qbA+KJjdy6VPUEZKS5a1UnPdwKTDPb2NP+201+p6Btr3nulg0zxuNp8ryI++s0TCumxnQvD0heJjWBZutilHsvYLFU=
