spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: night.fury.devs@gmail.com
    password: 8_forbidden_friendship
    protocol: smtp
    auth: true
    starttls: true
    quitwait: false
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: trip4u_db
      username: trip4u_user
      password: regular_user
      authentication-database: trip4u_db
      repositories:
        enabled: true
logging:
  file: logs/trip4u.log