spring:
  mails:
    host: smtp.gmail.com
    port: 587
    username: night.fury.devs@gmail.com
    password: 8_forbidden_friendship
    protocol: smtp
    auth: true
    starttls: true
    quitwait: false
  data:
    mongodb:
      repositories:
        enabled: true
logging:
  file: logs/trip4u.log

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      username: trip4u_user
      password: regular_user
      database: trip4u_db
      authentication-database: trip4u_db
  rabbitmq:
    username: trip4u_user
    password: regular_user
    host: localhost
    port: 5672
  security:
    cors:
      origins:
        - "http://localhost:4200"

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://trip4u_user:regular_user@ds011943.mlab.com:11943/heroku_1c7lh3rw
  rabbitmq:
    username: ONA0AjsB
    password: 7WsEaN7KoiWKD-hDG3zCzbVfgNbmp0vO
    host: running-blackberry-60.bigwig.lshift.net
    port: 10184
    virtual-host: BItUyqwrb4Dq
  security:
    cors:
      origins:
        - https://project-762377074824993679.firebaseapp.com
